### ISSUE TITLE
When Watching A Stream It Doesnt Say "Live" 

### ISSUE THREAD

**Issue by Dianolve** [Timeraa/PreMiD#16]
Im not sure if this is a feature or a bug lol

but whenever i watch a livestream on youtube it doesnt say "live"

I thought it was going to say live but it just went down from 57 mins

![image](https://user-images.githubusercontent.com/43133178/47249417-e2176b00-d45e-11e8-8bc0-b2e88d86008a.png)

**Comment by Timeraa** [comment]
Sorry that's a thing I can only make if and when we get partnered up with Discord
