### ISSUE TITLE
SuperAnimes.site

### ISSUE THREAD

**Issue by Maiker404** [Timeraa/PreMiD#25]
**Opinion**
If I could add the function to the SuperAnimes site I would be grateful.
I really liked the initiative!

**Comment by Timeraa** [comment]
I'll take a look at it, the url is "https://www.superanimes.site/" right?

**Comment by Maiker404** [comment]
Yes!


Em ter, 20 de nov de 2018 às 08:53, Florian Metz <notifications@github.com>
escreveu:

**Comment by Timeraa** [comment]
There's nothing on that page? When i load it it shows plain emptiness.

**Comment by Maiker404** [comment]
Ahn is a well used anime site, and to appear!
https://www.superanimes.site/
Good and a Brazilian site of anime maybe that's the problem!

**Comment by Fruxh** [comment]
Hey @Maiker404,

I had serious trouble with this site because of the country restriction.
But https://www.superanimes.site/ should be there in the next update ;)

**Comment by Maiker404** [comment]
Ok ,thanks! :D
