### ISSUE TITLE
Use "Listening" and "Watching" in some cases.

### ISSUE THREAD

**Issue by leoteodoro** [Timeraa/PreMiD#27]
Until today I thought that Discord doesn't accept to change the status to listening or watching, just playing, as many developers said to me that it wasn't possible, but someone from a Discord server told me that It is possible
https://discordapp.com/developers/docs/topics/gateway#activity-object-activity-types
![](https://cdn.discordapp.com/attachments/481508189591044096/514523232888553472/unknown.png)

could you guys please consider using this? thank you by now!

**Comment by Fruxh** [comment]
Hey leoteodoro,

thank you for that hint.
Our developers will definitely look into this. ^^

**Comment by Voknehzyr** [comment]
Discord RPC doesn't support activity types as far I know.
This documentation made for bots or selfbots.

**Comment by BitesizedLion** [comment]
This does not work with the way PreMiD displays rich presence.
