### ISSUE TITLE
Album Art for YouTube Music

### ISSUE THREAD

**Issue by SupaSickWog** [Timeraa/PreMiD#28]
**Is your feature request related to a problem?**
No this isn't a problem it can be done whenever. Download album art and show it on the rich presence kinda like spotify.

**Describe alternatives you've considered**
None, This app is pretty cool for aesthetic purposes.

**Additional context**
![image](https://user-images.githubusercontent.com/20286530/48888899-395a9200-ee88-11e8-96f5-6445f172fda7.png)

**Comment by SupaSickWog** [comment]
Also thanks for looking into my requests and responding fast, you are a nice dev.

**Comment by Timeraa** [comment]
Really sorry to say but this is restricted to Spotify at this time, we contacted Discord and hope for a Response soon. But we will most likely need to get partnered with them which is a rare thing to happen.
