### ISSUE TITLE
YouTube.com/TV

### ISSUE THREAD

**Issue by frozaum** [Timeraa/PreMiD#30]
**What's the name of the service?**
the version of Youtube TV Mode (https://www.youtube.com/tv)

**Why do you want support for this service?**
Because of the feature "to add videos on a queue", i want to show to my friends what i'm watching on the queue

**Comment by Timeraa** [comment]
Will take a look at it!

**Comment by frozaum** [comment]
thanks

**Comment by Timeraa** [comment]
Added in the next version! Thanks for suggesting. 👍

**Comment by frozaum** [comment]
please reopen this, because this got removed and still no answer to this day
