### ISSUE TITLE
Crunchyroll

### ISSUE THREAD

**Issue by Nishiki1** [Timeraa/PreMiD#43]
**What's the name of the service?**
Ex. www.youtube.com | YouTube

**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
Tell us why you want to have support for this website. Please don't just tell us "I use it all the time"

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image

**Comment by Timeraa** [comment]
#24
