### ISSUE TITLE
Doesn't detect twitch.tv stream

### ISSUE THREAD

**Issue by LBlend** [Timeraa/PreMiD#46]
**Describe the bug**
It seems like it can't detect twitch.tv streams even though it says you support it in your readme

It works on every other site. I've tried to relaunch the browser, the windows program and discord itself. Nothing seems to fix the issue

**To Reproduce**
1. Install extension
2. Install program
3. Open a twitch.tv stream

**Expected behavior**
Should send the rich presence data to discord

**Screenshots**
http://iamavirg.in/b0833b19865.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)
 - Version V1.2

**Comment by Timeraa** [comment]
Fixed in the next version, coming really soon!
