### ISSUE TITLE
Roblox Support 

### ISSUE THREAD

**Issue by Sazzo** [Timeraa/PreMiD#48]
**What's the name of the service?**
Roblox | web.roblox.com

**What should the Presence display?**
Information about the game the user is playing.

**Why do you want support for this service?**
It's a very famous game, it would be nice to have it on my Discord status.

**Are you able to provide an image for the service? (512x512 minimum)**
https://web.roblox.com/favicon.ico

**Comment by Voknehzyr** [comment]
This isn't a music or video service, go look for another solutions.

**Comment by BitesizedLion** [comment]
You cannot gain information about what the user is playing from the application the user would need to have their status open to all people(on their Roblox profile). And PreMiD is mostly for media(Videos, Music, And that.) And Roblox is mainly targeted towards younger kids (13 & below) and you have to be 13 to register to discord in the first place. So I suggest you go find something else

**Comment by Sazzo** [comment]
Oh, I forgot that part, sorry I think I went too far with my ideas.
