### ISSUE TITLE
The "disable" option won't disable PreMiD

### ISSUE THREAD

**Issue by CCreativeCND** [Timeraa/PreMiD#49]
**Describe the bug**
The "disable" option won't disable PreMiD.

**To Reproduce**
1. Install PreMiD Chrome extension.
2. Click on PreMiD extension icon and select disable.
3. Watch a video on any supported site and see PreMiD on Discord shos what you are watching.

**Expected behavior**
When I hit "disable", I expected it to disable PreMiD.

**Screenshots**
https://imgur.com/a/7jRh1aL

**Desktop:**
 - OS: Windows 7 Home Premium
 - Browser: Chrome
 - Version: Client v1.2, Extension v1.2.52

**Comment by Fruxh** [comment]
Hey @CCreativeCND,

it seems like that you have to reload the page/open a new tab if you want to disable PreMiD.
But you can enable it if it's running. I think Timeraa will take a look on it.

Thanks for reporting;)

Regards
-- Fruxh

**Comment by Timeraa** [comment]
Will take a look at it really soon!

**Comment by CCreativeCND** [comment]
Thanks!

**Comment by xPazz** [comment]
@CCreativeCND temp fix is to just exit the desktop app and reopen it when you want it back

**Comment by Timeraa** [comment]
Fixed in the next Version!

Thanks for reporting.

~ Timeraa

**Comment by MalwareMix** [comment]
wtf when i uninstalled it's still in startup care to explain?????? and how do I delete???
