### ISSUE TITLE
Groove Music

### ISSUE THREAD

**Issue by julienperrault** [Timeraa/PreMiD#68]
**What's the name of the service?**
Ex. Groove Music (Windows)

**What should the Presence display?**
Informations about the current music

**Why do you want support for this service?**
Groove Music is the default music player of Windows 10.

**Are you able to provide an image for the service? (512x512 minimum)**
https://img.icons8.com/windows/1600/microsoft-groove.png

**Comment by Fruxh** [comment]
Hey @julienperrault,

we can't support programs because we're coding for web services.

Sincerly
- Fruxh
