### ISSUE TITLE
Firefox Extension

### ISSUE THREAD

**Issue by nobobo1234** [Timeraa/PreMiD#7]
**Is your feature request related to a problem? Please describe.**
Yes, I have the problem that the chrome extension doesn't work when added to firefox.

**Describe the solution you'd like**
I'd like the chrome extension to be ported to firefox so I can use it with my firefox browser (and adding to the addon-store is free 😉 

**Describe alternatives you've considered**
I would rather not switch to Chrome, its slow lol

**Comment by Timeraa** [comment]
I will look into creating an addon for Firefox.

**Comment by Timeraa** [comment]
Just a little note: If anyone wants to create YT Presence for their Browser, go ahead! The extension basically just injects a script into the HTML file of YouTube & YouTube Music.

**Comment by Timeraa** [comment]
Okay, closing this issue because Version 1.0 (releasing really soon) will have Extensions for Firefox, Opera and Chrome.

**Comment by Timeraa** [comment]
Quick update on this, I am having a lot trouble with the Firefox extension, some JQuery events don't register, socket.io doesn't work at all. If someone knows why feel free to comment. :l

**Comment by Timeraa** [comment]
Yeah one sec

**Comment by Timeraa** [comment]
Okay i pushed it to Branch 1.0

**Comment by Timeraa** [comment]
Feel free to join the new YT Presence Discord Server for faster responses.
https://discord.gg/Kw7WaYn

**Comment by xPazz** [comment]
summary of issues
* slightly different format for manifest (just different permission names)
* almost all code in the extension is made to work for chrome, you'll need to get the firefox equivalents
* socketio needs slightly different configuration (it works in firefox.. in case you are wondering)
* permissions for manifest are seperated more in firefox
* probably other stuff but idk

**Comment by Timeraa** [comment]
If it works, are you able to give me a link to a site/extension that uses it?

**Comment by xPazz** [comment]
see the following for help with socketio:
https://stackoverflow.com/questions/22987626/socket-io-in-firefox-add-on
https://stackoverflow.com/questions/29411248/firefox-chrome-addon-socketio
https://stackoverflow.com/questions/17298950/socket-io-not-working-in-chrome-and-firefox-on-windows

@Timeraa

**Comment by Timeraa** [comment]
Will take a look at them after i finished the update.

**Comment by nobobo1234** [comment]
Any update on this?

**Comment by Timeraa** [comment]
Will try to work on a Firefox extension when i finished the next Update of the Extension (Should be out in a few days)

**Comment by allanf181** [comment]
firefox already has rich presence extension

**Comment by Timeraa** [comment]
Currently working really hard for a Firefox extension! Give me a few days 😉

**Comment by Timeraa** [comment]
If you want to test the alpha versions of the Firefox extension, clone the repo and import the Firefox extension for testing. Report any bugs on Firefox in here.

**Comment by Timeraa** [comment]
Almost done with the Extension!

Only need to fix the missing support and upload it to the addon store

~ Timeraa

**Comment by Fruxh** [comment]
*after 3 months*

**Comment by Navneet-Suresh** [comment]
[Firefox Extension](https://github.com/PreMiD/PreMiD#firefox-extension-installation) addon is not found.
Any other way to get the extension for firefox?

**Comment by Voknehzyr** [comment]
> [Firefox Extension](https://github.com/PreMiD/PreMiD#firefox-extension-installation) addon is not found.
> Any other way to get the extension for firefox?

FireFox decided to disable PreMiD because of various reasons.... ugh, Thats why you don't find it on the store rn, i hope to get it back soon!

**Comment by codingJWilliams** [comment]
@Voknehzyr Any way to install it while it's down?

**Comment by codingJWilliams** [comment]
bump?

**Comment by Fruxh** [comment]
https://wiki.premid.app/installation/extension

**Comment by codingJWilliams** [comment]
Thanks!
