### ISSUE TITLE
Oauth2 broken on website

### ISSUE THREAD

**Issue by ThatTonybo** [Timeraa/PreMiD#70]
**Describe the bug**
On the website login, the oauth2 redirect URI is set to `localhost:8080`

**To Reproduce**
1. Go to [premid.app](https://premid.app)
2. Click "Login"
3. On authorization redirect, see the URL box

**Expected behavior**
It should use `premid.app` on return.

**Screenshots**
![image](https://user-images.githubusercontent.com/28176227/50407855-86d17280-082b-11e9-8f97-7cca5c6f96f8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Pro 1809
 - Browser [e.g. chrome, safari] Firefox Quantum Nightly
 - Version [e.g. 22] 64 (see below)
![image](https://user-images.githubusercontent.com/28176227/50407861-9f418d00-082b-11e9-949c-61af1ee41c47.png)

**Additional context**
If you replace `localhost:8080` with `premid.app`, it errors as well:
![image](https://user-images.githubusercontent.com/28176227/50407869-b97b6b00-082b-11e9-8d2c-10ecf8f17ce1.png)

Awesome program as well. 👍

**Comment by Timeraa** [comment]
First of all thanks 😄 
Our current website is really old, its getting a huge upgrade really really soon :P
