### ISSUE TITLE
Dopamine

### ISSUE THREAD

**Issue by Rudyon** [Timeraa/PreMiD#76]
**What's the name of the service?**
http://www.digimezzo.com/software/dopamine/ | Dopamine

**What should the Presence display?**
Informations about the current song.

**Why do you want support for this service?**
This software is what I have switched to for listening to music. I would like my friends to see what ı am listening to.
![image](https://user-images.githubusercontent.com/41804126/50575013-056a7900-0e05-11e9-9df5-02b8793d908d.png)

**Comment by Fruxh** [comment]
Hey @Rudyon,

we can't support programs because we're coding for web services.

Sincerly
~ Fruxh

**Comment by KaleidonKep99** [comment]
Someone could add support for programs by communicating with them via pipes though.

**Comment by Fruxh** [comment]
Go on then ;)
